---
- name: user creation
  hosts: all
  tasks: 
   - name: user create
     user:
      name: chikun
      password: rasmi
      comment: "my world"
      shell: /bin/bash
      uid: 21232
      home: /home/ubuntu/chikun
