---
- name: install application
  hosts: all
  tasks: 
   - name:  s/w install
     apt:
      name:  "{{item.a}}"
      state: "{{item.b}}"
      update_cache: "{{item.c}}"
     with_items:
      - {a: tree,b: present,c: no}
      - {a: tomcat9,b: present,c: yes}
      - {a: openjdk-8-jdk,b: present,c: yes}
      